language: node_js
node_js:
- '0.12'
deploy:
  provider: heroku
  api_key:
    secure: ypFh8oQEP1KacFVFG8T5MGsorOFt5MDmEiPWT89HjXVQ/G4xRMSXGFCxUXhmlWl9gK3Mz9FTKjU+qOief4YH3zqnZ0yy0mLo9u3DGlfZPBHjLE/YCGh2AwCXzeB5V5DrV4TW1JKvRC+fH+/YTsHNwwAEhDrYHuysX+2t23bXn2GIRyMXDD506HDvjcFWU4cjfaEzeiXQWHvgIJYr292JgMeyxHwv/q6Vu7Pz/onF7TWR9+k9Hj3F8sObP7OTnh09WaSDHlkr1tAqCVaAaYRyZJnlbJa3e5+3sunjT1zupgT0dZNtm0mSCJ8Zyq7dTbN1DVEskixmtsLHRjNq6aO4jQrcHCOHwkeOlIdVnZCB73mRvGCQtEBld0UVZ3czTWTeRNKofR6dl7YYw1n4KLQAEIcI9cThMWtq6HAfXdy6JpMDEVi6CUSmRf2ojPQhwh5i9LIROjAGUEOzhpBA36dtTP0oq8YsHdwBGRKInIulUgPQjXhMSytLcHjzPyC1eUp7isn4+ZM23OgyKWqZmtfH2qpo7X+7bcKGd58dbyhQ0PnMlrXwVPr5FBpfY7jIzanp0fBwLzsTjPRp+qji7jN2tXUSvi8O6zFXODOWhbARV44dvuMukxopzBIEOpoZrS6dvDMaD2Ovt2wfo6kj/XRIOQmDvksb8l7fhVCzyqsslus=
  app: api-bergems-org
  on: master
notifications:
  slack:
    secure: MG/BaXyTt6t6fjoFuuGwXHv/5jHLZoTu+HgNA+tWNCaI4NEYQomGRdhnAoda9v4Hy+tOHrkdmv6UE0rhuNxA/jF2NUk3VUBtIvLxPw5yIkcZCkMBwB7S97cMVpETDrnZvUVp6wVGDEUplIfvDjzNSM97Dq49PmUmnqK7ET8YqbtXAwzwH2IYoPUlgMSm77Y0VATEkbc1TY5+5foSVPqoS2OZFDpu9XtNKeCPY0BQIZmShDsD6AEKpu2a/U1c490Baiqle41PtJxOpIAYfugf3Tu4SAjxXOAIJBnZOc/zdLC7J44wNqb1HRsSfsoeYDCDozQ7A2dhODBbSZNfChUi50rKI5CoNR2AxER8/t6mIAS4gvmLvwkbmR9erZoXPNBTXFaAYNtRH4umZPvRUVOks74f82xiBCpdWDzI1YGYoiSlPndpblpaeP0JO/PnZp0OVlerSyf1csebbKk9KKdS7wgg9kk88CPkf+JDJOUK4LPiX11GHUHz1Y4BaZemOW3xKFZ+13DfNjEqelUP317vxCgxDMVPUGD/aUZy0T+mLcMZt6/vKsMnTJsjgssKaVAVcBwYe/Qe5Y4KIwJGZS851YwXD3kUWZtm401hrrtdVZ0tlZDXo5RINDRkFRcmN1hvjyS5AhWr3BEBLsObaua7CrUWtvTOR+x+eVkwidfAeHA=
