postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: mcems
    POSTGRES_PASSWORD: mcems
    POSTGRES_DB: mcems
web:
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
